# Generated by Django 5.0.1 on 2024-02-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Degree', models.CharField(max_length=100)),
                ('Field', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField()),
                ('State', models.CharField(max_length=50)),
            ],
        ),
    ]
